Hbo 3
NiakhaichykVitaliy/Sample pull request #3
Opened 2024-11-24 15:44 UTC by NiakhaichykVitaliy

2024-11-24 19:35 UTC, DerevyagoKonstantin requested changes

2024-11-24 19:35 UTC, DerevyagoKonstantin commented on app/src/main/java/com/example/sample/MainActivity.java
> +    private RecyclerView recyclerView;
это всё должно быть в отдельном фрагменте, который будет на активити

2024-11-24 19:35 UTC, DerevyagoKonstantin commented on app/src/main/java/com/example/sample/Pokemon.java
> +    public String getNamePokemon() {
обычно в таких классах-модельках делают геттегры и сеттеры для всех параметров

2024-11-24 19:35 UTC, DerevyagoKonstantin commented on app/src/main/java/com/example/sample/PokemonAdapter.java
> +        this.pokemonList = pokemonList;
список лучше передавать отдельной функцией, а не в конструкторе. иначе тебе надо будет заново создавать весь адаптер при изменении списка

2024-11-24 19:35 UTC, DerevyagoKonstantin commented on app/src/main/java/com/example/sample/PokemonAdapter.java
> +        holder.pokemonName.setText(pokemon.getNamePokemon());
давай лучше во вьюхолдере сделаем функцию bind, в которой будут сеттиться все параметры

2024-11-24 19:35 UTC, DerevyagoKonstantin commented on app/src/main/res/layout/list_pokemon.xml
это скорее pokemon_item

2024-11-24 19:35 UTC, DerevyagoKonstantin commented on app/src/main/res/layout/list_pokemon.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
зачем тут линер?

2024-11-24 19:35 UTC, DerevyagoKonstantin commented on app/src/main/res/layout/list_pokemon.xml
> +    tools:context=".MainActivity">
при чем тут мейн активити?

2024-11-24 19:35 UTC, DerevyagoKonstantin commented on app/src/main/res/layout/list_pokemon.xml
> +        <RelativeLayout
зачем релатив?

2024-11-24 19:35 UTC, DerevyagoKonstantin commented on app/src/main/res/values/dimens.xml
> +    <dimen name="image_size">80dp</dimen>
лучше сразу указать какой именно картинки. например, pokemon_image_size или типо того

2024-11-24 19:35 UTC, DerevyagoKonstantin commented on app/src/main/res/values/strings.xml
> +    <string name="picachu_image">https://www.film.ru/sites/default/files/images/10(186).jpg</string>
урлы нет смысла выносить в ресурсы, если только ты не собираешься их как то менять для разных языков/стран/размеров девайса и т.д.

в принципе мы потом будем брать их из запроса, так что давай лучше урлы и имена просто в классе обычными строчками

2024-11-24 19:35 UTC, DerevyagoKonstantin commented on gradle/libs.versions.toml
> +playServicesAdsLite = "23.5.0"
а зачем тебе рекламные либы?

2024-11-26 19:45 UTC, DerevyagoKonstantin requested changes

2024-11-26 19:45 UTC, DerevyagoKonstantin commented on app/src/main/java/com/example/sample/MainActivity.java
> +        PokemonFragment pokemonFragment = new PokemonFragment();
тут не ошибка, но лучше привыкай создавать фрагменты через статический метод (например getInstance(). вот типо как для активити startActivity()), чтобы случайно не передать какие нибудь аргументы в конструктор фрагмента, если они будут нужны (аргументы надо засовывать в бандл, чтобы они не потерялись при пересоздании, и про это легко забыть. а при вызове статического метода ты скорее всего про это вспомнишь)

2024-11-26 19:45 UTC, DerevyagoKonstantin commented on app/src/main/java/com/example/sample/MainActivity.java
> +        FragmentTransaction fragmentTransaction = getSupportFragmentManager().beginTransaction();
тоже не ошибка, но вроде бы эти функции транзакции возвращают тоже транзакцию и можно цепочкой сделать:
```
getSupportFragmentManager().beginTransaction()
    .replace(R.id.fragment_container, PokemonFragment.getInstance())
    .commit();
```

2024-11-26 19:45 UTC, DerevyagoKonstantin commented on app/src/main/java/com/example/sample/PokemonAdapter.java
> +    public static class PokemonViewHolder extends RecyclerView.ViewHolder {
лучше наверное вынести внутренний класс вниз, чтобы не мешать с функциями

2024-11-26 19:45 UTC, DerevyagoKonstantin commented on app/src/main/java/com/example/sample/PokemonAdapter.java
> +    public static class PokemonViewHolder extends RecyclerView.ViewHolder {
а почему статик?

2024-11-26 19:45 UTC, DerevyagoKonstantin commented on app/src/main/java/com/example/sample/PokemonFragment.java
> +    private List<Pokemon> pokemonList;
кажется список не надо делать глобальной переменной класса. можно просто в функции создать

2024-11-26 19:45 UTC, DerevyagoKonstantin commented on app/src/main/java/com/example/sample/Pokemon.java
> +    private String namePokemon;
тоже не ошибка, но нет смысла добавлять `Pokemon` к параметрам внутри класса `Pokemon` - это и так понятно)

2024-11-28 06:27 UTC, NiakhaichykVitaliy commented on app/src/main/java/com/example/sample/PokemonAdapter.java
> +    public static class PokemonViewHolder extends RecyclerView.ViewHolder {
статический класс не хранит ссылку на свои экземпляры класса, что не приводит к утечке памяти

2024-11-28 08:30 UTC, DerevyagoKonstantin requested changes

2024-11-28 08:30 UTC, DerevyagoKonstantin commented on app/src/main/java/com/example/sample/MainActivity.java
> +        fragmentTransaction.commit();
А чего коммит отдельной строчкой? Реплейс вроде бы тоже объект транзакции возвращает

2024-11-28 08:30 UTC, DerevyagoKonstantin commented on app/src/main/java/com/example/sample/PokemonAdapter.java
> +    public static class PokemonViewHolder extends RecyclerView.ViewHolder {
Я может уже джаву забыл, но разве Статик для класса тут нужен?

2024-11-28 08:30 UTC, DerevyagoKonstantin commented on app/src/main/res/layout/fragment_pokemon.xml
> +        android:text="@string/title_list_pokemon"
Если я правильно помню, то тут надо просто text на title поменять и тогда не надо будет в классе сетать строку

2024-11-30 18:55 UTC, DerevyagoKonstantin approved these changes

2024-12-05 08:21 UTC, merged