[HBO-4] Create ViewPagerFragment
NiakhaichykVitaliy/Sample pull request #4
Opened 2024-11-30 12:40 UTC by NiakhaichykVitaliy

Create ViewPagerAdapter
Edit fragmentTransaction
Add icon to TabLayout

2024-11-30 19:05 UTC, DerevyagoKonstantin requested changes

2024-11-30 19:05 UTC, DerevyagoKonstantin commented on app/src/main/java/com/example/sample/PokemonViewPagerAdapter.java
> +    List<Pokemon> pokemonList = new ArrayList<>();
а этот лист зачем?

2024-11-30 19:05 UTC, DerevyagoKonstantin commented on app/src/main/java/com/example/sample/PokemonViewPagerAdapter.java
> +        if (position == 0) {
кажется через `switch` красивее будет

2024-11-30 19:05 UTC, DerevyagoKonstantin commented on app/src/main/java/com/example/sample/PokemonViewPagerFragment.java
> +public class PokemonViewPagerFragment extends Fragment {
этот фрагмент не нужен. можешь вьюпейджер и табы вынести сразу на активити

2024-11-30 19:05 UTC, DerevyagoKonstantin commented on app/src/main/java/com/example/sample/PokemonViewPagerFragment.java
> +                    tab.setText(R.string.pokemon_fragment_1);
я тут не уверен, но разве нельзя это сразу в хмлке задать?

2024-11-30 19:05 UTC, DerevyagoKonstantin commented on app/src/main/res/drawable-anydpi/poke_ball.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
если у тебя есть векторная картинка, то ты можешь положить ее одну в просто папку drawable и не создавать копии в разных папках с разным разрешением (это надо для растровых картинок, которые не умеют скейлиться для разных разрешений)

2024-11-30 19:05 UTC, DerevyagoKonstantin commented on app/src/main/res/layout/viewpager_pokemon.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
почему релатив?

2024-11-30 19:05 UTC, DerevyagoKonstantin commented on app/src/main/java/com/example/sample/PokemonViewPagerFragment.java
> +                    tab.setText(R.string.pokemon_fragment_1);
а текст вообще нужен, если у тебя есть картинка?

2024-12-01 11:59 UTC, NiakhaichykVitaliy commented on app/src/main/res/layout/viewpager_pokemon.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
android:layout_alignParentBottom="true" не поддерживается Линнером

2024-12-01 11:59 UTC, NiakhaichykVitaliy commented on app/src/main/java/com/example/sample/PokemonViewPagerFragment.java
> +                    tab.setText(R.string.pokemon_fragment_1);
могу убрать, но делал, чтобы показать и то и другое

2024-12-01 12:01 UTC, NiakhaichykVitaliy commented on app/src/main/java/com/example/sample/PokemonViewPagerFragment.java
> +                    tab.setText(R.string.pokemon_fragment_1);
можно, но нужно создавать отдельные тайтлы, переделаю

2024-12-04 22:05 UTC, DerevyagoKonstantin requested changes

2024-12-04 22:05 UTC, DerevyagoKonstantin commented on app/src/main/java/com/example/sample/PokemonViewPagerActivity.java
> +public class PokemonViewPagerActivity extends AppCompatActivity {
да зачем тебе дополнительное активити?) просто вынеси всё что есть тут в MainActivity

2024-12-04 22:05 UTC, DerevyagoKonstantin commented on app/src/main/res/layout/fragment_pokemon.xml
> +
лишняя пустая строка

2024-12-04 22:05 UTC, DerevyagoKonstantin commented on app/src/main/res/layout/viewpager_pokemon.xml
> +        android:layout_height="wrap_content">
можно сразу закрыть тэг

2024-12-08 18:31 UTC, DerevyagoKonstantin requested changes

2024-12-08 18:31 UTC, DerevyagoKonstantin commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".PokemonViewPagerActivity" />
это лишнее

2024-12-08 18:31 UTC, DerevyagoKonstantin commented on app/src/main/java/com/example/sample/PokemonViewPagerAdapter.java
> +                PokemonFragment.getInstance();
я вот не заметил сначала, но этот свич бесполезный, так как ты в нем ничего не возвращаешь. у тебя тут только один ретурн в конце функции

2024-12-08 19:57 UTC, DerevyagoKonstantin approved these changes

2024-12-09 06:06 UTC, merged

2024-12-09 06:58 UTC, DerevyagoKonstantin approved these changes