[HBO-7]
NiakhaichykVitaliy/Sample pull request #7
Opened 2024-12-15 10:55 UTC by NiakhaichykVitaliy

2024-12-16 19:29 UTC, DerevyagoKonstantin requested changes

2024-12-16 19:29 UTC, DerevyagoKonstantin commented on pokemon/.gitignore
> +/build
разве гитигнор тут нужен?

2024-12-16 19:29 UTC, DerevyagoKonstantin commented on pokemon/build.gradle.kts
> +plugins {
кажется в этом файле много необязательной инфы) ты его походу скопировал из аппа. но в аппе основной гредловый файл. во вспомогательных модулях вроде бы можно опустить много настроек, которые есть в аппе. если я правильно помню, то в `android { }` важно указать `namespace` и возможно настройки котлина

2024-12-16 19:29 UTC, DerevyagoKonstantin commented on pokemon/consumer-rules.pro
чот мне кажется этот файл не нужен)

если я правильно помню, то этот файл используется вместо `proguard-rules.pro`, если ты собираешь модуль как библиотеку, которая будет внедряться в другие проекты. если же это просто модуль твоего проекта, то по дефолту будет использоваться `proguard-rules.pro`, в котором указываются правила что "отрезать", а что нет при обфускации (это процесс отрезания лишний неиспользуемых классов во время сборки apk-шки, чтобы она весила меньше)

2024-12-16 19:29 UTC, DerevyagoKonstantin commented on pokemon/src/androidTest/java/com/example/pokemon/ExampleInstrumentedTest.kt
> +package com.example.pokemon
думаю тебе пока что не нужны UI тесты)

2024-12-16 19:29 UTC, DerevyagoKonstantin commented on pokemon/src/main/AndroidManifest.xml
> +<manifest xmlns:android="http://schemas.android.com/apk/res/android">
если внутри тега ничего нет, то можно сразу закрывающий использовать

2024-12-16 19:29 UTC, DerevyagoKonstantin commented on pokemon/src/main/java/com/example/pokemon/model/Pokemon.kt
> +    val image: String
в котлине если перечисления идут с новой строчки каждый элемент, то в конце тоже ставится запятая. это называется trailling comma

2024-12-16 19:29 UTC, DerevyagoKonstantin commented on pokemon/src/main/java/com/example/pokemon/viewmodel/PokemonViewModel.kt
> +                "Pikachu1",
обоснуй)

2024-12-16 19:29 UTC, DerevyagoKonstantin commented on pokemon/src/main/res/drawable/poke_ball.png
а это почему перенеслось в модуль покемонов, если используется и связано с табами, которые на активити?

2024-12-16 19:29 UTC, DerevyagoKonstantin commented on pokemon/src/main/res/values/colors.xml
> +<resources>
это точно связано только с модулем покемонов?

2024-12-16 19:29 UTC, DerevyagoKonstantin commented on pokemon/src/main/res/values/dimens.xml
> +    <dimen name="login_small">30dp</dimen>
тут явно не все про покемонов и не должно быть в этом модуле

2024-12-16 19:29 UTC, DerevyagoKonstantin commented on pokemon/src/main/res/values/strings.xml
> +    <string name="app_name">Sample</string>
и тут

2024-12-16 19:29 UTC, DerevyagoKonstantin commented on pokemon/src/main/res/values/themes.xml
> +    <style name="Base.Theme.Sample" parent="Theme.Material3.DayNight.NoActionBar">
тут тема аппликейшена, почему она в модуле покемонов?

2024-12-16 19:29 UTC, DerevyagoKonstantin commented on pokemon/src/test/java/com/example/pokemon/ExampleUnitTest.kt
> +package com.example.pokemon
тесты пока что можешь удалить

2024-12-16 19:29 UTC, DerevyagoKonstantin commented on app/src/main/java/com/example/sample/Pokemon.java
> -public class Pokemon {
а этот класс разве не используется в джавовом фрагменте?

2024-12-17 14:16 UTC, NiakhaichykVitaliy commented on pokemon/src/main/java/com/example/pokemon/viewmodel/PokemonViewModel.kt
> +                "Pikachu1",
это при тесте я отличаю фрагменты)

2024-12-17 14:21 UTC, NiakhaichykVitaliy commented on app/src/main/java/com/example/sample/Pokemon.java
> -public class Pokemon {
использовался, но возникали конфликты, т.к. было 2 класса Pokemon. Поэтому я java класс удалил и работают с новым kotlion классом из модуля Pokemon

2024-12-17 19:30 UTC, DerevyagoKonstantin requested changes

2024-12-17 19:30 UTC, DerevyagoKonstantin commented on app/src/main/java/com/example/sample/Pokemon.java
> -public class Pokemon {
какие конфликты? у тебя же эти классы в разных пакетах и используются в разных классах - не должно быть никаких конфликтов

2024-12-17 19:30 UTC, DerevyagoKonstantin commented on pokemon/build.gradle.kts
> +    compileSdk = 34
разве `compileSdk` обязательно?

2024-12-17 19:30 UTC, DerevyagoKonstantin commented on pokemon/src/main/AndroidManifest.xml
> +<manifest xmlns:android="http://schemas.android.com/apk/res/android"/>
вообще манифест тут наверное даже удалить можно

2024-12-17 19:30 UTC, DerevyagoKonstantin commented on pokemon/src/main/java/com/example/pokemon/ui/PokemonFragment.java
так, подожди, я же в задаче писал перенести только котлиновские файлы в новый модуль. старый джавовый фрагмент и пейджер адаптер не должны быть в этом модуле. этот новый модуль должен в себе содержать только новый котлиновский фрагмент и всё с ним связанное. мы потом вообще сделаем так, чтобы из него в апп модуле был виден только фрагмент, который можно только отобразить. а вся логика, модельки и т.д. - это внутренняя реализация, которую другим модулям знать не надо. считай это как паблик и прайвит. сейчас у тебя всё паблик, но мы потом переделаем так, чтобы пабликом было минимально возможное

2024-12-17 19:30 UTC, DerevyagoKonstantin commented on pokemon/src/main/java/com/example/pokemon/viewmodel/PokemonViewModel.kt
> +                "Pikachu1",
давай тогда сделаем коряво в старом, а в новом будет всё как надо)

2024-12-17 19:30 UTC, DerevyagoKonstantin commented on pokemon/src/main/res/layout/list_pokemon.xml
давай переименуем в `item_pokemon` - тут всё таки отдельный айтем списка, а не весь список

2024-12-17 19:30 UTC, DerevyagoKonstantin commented on pokemon/src/main/res/layout/list_pokemon.xml
> +            android:layout_toEndOf="@+id/pokemon_image" />
а это что такое?)

2024-12-18 06:03 UTC, NiakhaichykVitaliy commented on pokemon/build.gradle.kts
> +    compileSdk = 34
да, без него не запускается

2024-12-18 12:45 UTC, DerevyagoKonstantin approved these changes

2024-12-19 06:01 UTC, merged